### ISSUE TITLE
Feature: add Stripe-style 'pick your language' examples

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#117]
Arc 6 docs currently:

![image](https://user-images.githubusercontent.com/172594/61291355-379e5f80-a7c6-11e9-90c1-e6cacae0bbd6.png)

Which means python folk have to look at JS and Ruby, etc.

Proposing something like https://stripe.com/docs/billing/quickstart:

![image](https://user-images.githubusercontent.com/172594/61291425-66b4d100-a7c6-11e9-9f61-9bbfdebf3e86.png)

 - Client side JS is just setting a `translateX` to show the right example (pretty low overhead). We can do this directly or have it generated by Svelte. 
 - Setting it once would change all examples on the page
 - We can store preferred lang in a cookie maybe? 

What do you think? I can do it if you want.

**Comment by brianleroux** [comment]
I think 

FUCK YA

esp as we add other runtimes this will be hugely needed

**Comment by mikemaccana** [comment]
We did this in the V6 docs site we could port the code to the V8 docs site....

**Comment by tbeseda** [comment]
arc.codes now has a tabbed interface for code blocks in different languages. I think one idea that hasn't been implemented yet is to change other code samples on the same view, or even storing the preference across the site 
Closing this and we can continue talking further improvements in #239
