### ISSUE TITLE
Document normal 404 behavior

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#119]
From that I've observed, this seems to be correct:

> If no lambda exists for a route, a GET request will end up going to `src/http/get-index`?

Is that accurate? Can I add docs for that (maybe using middleware to intercept the 404 requests and separate them from the regular requests to `/`)?

**Comment by brianleroux** [comment]
yes to both! recently wrote the code for 404 detection for the sandbox and aim to get that into `arc.http`

**Comment by mikemaccana** [comment]
Done! 🙂
