### ISSUE TITLE
Document Arc 6 `type` change

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#124]
Arc 5 had: `type: 'text/html; charset=utf8',`

In Arc 6 it it seems to be: 
    `headers: { 'content-type': 'text/html; charset=utf8' },`

**Comment by brianleroux** [comment]
This is documented! We should add detail to the upgrade guide tho

**Comment by ryanblock** [comment]
That should have been present already here: https://arc.codes/primitives/http#req

However, we have just updated the Upgrade Guide, which should make these changes much clearer: https://arc.codes/guides/upgrade
