### ISSUE TITLE
Version 6: Document that req.query is now req.queryStringParameters

### ISSUE THREAD

**Issue by gr2m** [architect/arc.codes#127]
**Describe the issue**

I've just upgraded to v6 and found that `req.query` is undefined, it looks like `req.queryStringParameters` is the new property to use?

I did not find any note on this in the migration guide. Sorry if I missed something

**Comment by gr2m** [comment]
`req.method` is now `req.httpMethod`

**Comment by ryanblock** [comment]
That was already present here: https://arc.codes/primitives/http#req

However, we have just updated the Upgrade Guide here, which should make these changes much clearer! 

Thanks for your patience. https://arc.codes/guides/upgrade
