### ISSUE TITLE
Aws deploy issues

### ISSUE THREAD

**Issue by alexandru-calinoiu** [architect/arc.codes#132]
**Describe the issue**
Trying to deploy the quickstrat project to aws. I stumble on 2 issues:

- I need to know what permissions my account should have
- Tried the deploy with a root account, the deploy apparently worked the url I got for it just returns a 502 (works when running with sandbox)

**Steps to reproduce**
1. Do the quickstart tutorial with ruby
2. Try to do the deploy with `arc deploy`
3. Click on the result link

**Expected behavior**
Should behave the same as with `arc sandbox`

**Screenshots**
none

**Desktop**
Please complete the following information (if appropriate):
 - OS: Linux
 - Browser Firefox
 - Version 6.0.8

**Additional context**
None

**Comment by tritowntim** [comment]
@alexandru-calinoiu looking at your repo, did you try specifying a bucket?

https://github.com/alexandru-calinoiu/arc-test/blob/master/.arc

In my experience, you have to create the bucket manually as well.

**Comment by brianleroux** [comment]
can you share the .arc file and the exact console output from `arc deploy` /  error text you are seeing ?

**Comment by alexandru-calinoiu** [comment]
> @alexandru-calinoiu looking at your repo, did you try specifying a bucket?
> 
> https://github.com/alexandru-calinoiu/arc-test/blob/master/.arc
> 
> In my experience, you have to create the bucket manually as well.

Yes I've created a new S3-bucket and specified it, it see 2 files in it 

![image](https://user-images.githubusercontent.com/679198/64666312-867f1300-d45e-11e9-8f80-8ab97059b6a5.png)

**Comment by alexandru-calinoiu** [comment]
> can you share the .arc file and the exact console output from `arc deploy` / error text you are seeing ?

https://github.com/alexandru-calinoiu/arc-test/blob/master/.arc

There is no output error, the deploy seems to work fine and then when trying to access the result link https://7drj1wqt1d.execute-api.us-east-1.amazonaws.com/staging, erro.

**Comment by brianleroux** [comment]
good catch, leaving this open so I can fix it trmw (or if you're feeling ambitious have a look!) the request sig was wrong: 

```ruby
def handler(req)
  {
    headers: { 'content-type': "text/html; charset=utf-8" },
    body: "<h1>Fuck Ya</h1>",
  }
end
```
fixes it! https://45q1uwez93.execute-api.us-east-1.amazonaws.com/staging

(was able to diagnose looking at cloudwatch logs in the console; part of the bug here is that the `arc logs src/http/get-index` didn't output the error … aws recently changed payload formatting so we need to fix that too)

thx for reporting!

**Comment by alexandru-calinoiu** [comment]
Thank you, it worked!

**Comment by brianleroux** [comment]
all good! software is frustrating 💩 and I swear at it all the time !
