### ISSUE TITLE
Quickstart: AWS_PROFILE default

### ISSUE THREAD

**Issue by shazron** [architect/arc.codes#141]
**Describe the issue**
Should AWS_PROFILE be required? According to the [AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) the `default` profile should be used if the environment variable is not set. Right now it is required.

**Steps to reproduce**
1. Unset `AWS_PROFILE`
2. Follow the `Try it in 30 seconds` at https://arc.codes
3. `arc deploy`
4. See error that says 'Failed to deploy missing AWS_PROFILE'

**Expected behavior**
Arc should use the `default` profile if `AWS_PROFILE` is not set

**Actual behavior**
Arc gives an error if `AWS_PROFILE` is not set.

**Workaround**
Add docs in the [Credentials setup doc](https://arc.codes/quickstart#local-credentials-file) for the user to add `AWS_PROFILE` instead

**Comment by brianleroux** [comment]
this got fixed a while ago / sorry for the silence shaz!
