### ISSUE TITLE
Exception when going to any key from Layout page

### ISSUE THREAD

**Issue by shazron** [architect/arc.codes#142]
## **Describe the issue**
Exception when going to https://arc.codes/reference/aws (as an example) from this page https://arc.codes/quickstart/layout

Other keys exhibit the same exception when navigated to.
![Screen Shot 2019-10-09 at 9 47 32 AM](https://user-images.githubusercontent.com/36107/66445580-d5c65c80-ea79-11e9-9be7-5e126f33c762.png)

## Fix:
`https://arc.codes/reference/aws` --> `https://arc.codes/reference/arc-config/aws` for all keys in the page

**Comment by douglasmccarroll** [comment]
I'm getting the same thing when I try to go from https://arc.codes/quickstart to https://arc.codes/guides/multiple-aws-accounts.

**Comment by tbeseda** [comment]
Thanks for reporting. Cleaning up some stale issues.
