### ISSUE TITLE
Quickstart: AWS bucket setup instruction is skipped (implied)

### ISSUE THREAD

**Issue by shazron** [architect/arc.codes#143]
**Describe the issue**
30 seconds is optimistic if the user already has a bucket. It is not pointed out in https://arc.codes/quickstart nor https://arc.codes/ "Try it in 30 seconds" that you will need to create or have a bucket beforehand.

There should be a link to https://arc.codes/reference/arc/aws to give "green" users guidance on what to do next so the QuickStart is successful.

I realize that the persona of a user using Architect might be an experienced AWS developer -- where I'm coming from is from a newbie user of Architect.

**Steps to reproduce**
1. Go to 'https://arc.codes/.'
2. Setup your credentials file
3. `arc deploy`
4. See error `Failed to deploy missing @aws in .arc`

Perhaps if the user is missing a key, point them to the key's reference page.

**Comment by brianleroux** [comment]
Thx for reporting this Shaz! (We create a bucket automatically now.)
