### ISSUE TITLE
Document special files + folders

### ISSUE THREAD

**Issue by ryanblock** [architect/arc.codes#144]
We should have a document dedicated to special files, folders, and deps within the Architect project. Examples:
- project manifests
  - `.arc`
  - `app.arc`
  - `arc.json`
  - `arc.yaml`
- static manifest
  - `$public/static.json`
- `src/`
  - `http`
  - `events`
  - etc.
- shared files
  - `src/shared`
  - `src/views`
- root `package.json`
  - doesn't influence per-function packages

**Comment by brianleroux** [comment]
agree! probs here https://arc.codes/quickstart/layout
