### ISSUE TITLE
Add changes to await lambdas to Arc 6 changelog

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#171]
Ryan mentioned ages ago: 

>  as you may know, arc 6 dep-free request/response signatures are different from arc <6; the new arc functions should allow for drop-in replacement, run your existing arc 5 dep-free lambda returns through res() and all should be well.

This isn't included in the https://arc.codes/guides/upgrade - that doc should have what the differences are added.

architect/architect#404

**Comment by brianleroux** [comment]
closing this! this feedback has dissipated now that we're 'standard' lambda
