### ISSUE TITLE
getting started content

### ISSUE THREAD

**Issue by brianleroux** [architect/arc.codes#213]
the new docs need fresh content for getting starting

https://github.com/architect/arc.codes.next/tree/master/src/docs/en/guides/get-started

prior art here:
- v6 https://github.com/architect/arc.codes/tree/master/public/quickstart
- v5 https://github.com/architect/v5.arc.codes/blob/master/src/shared/en/aws/quickstart.md
- v5 https://github.com/architect/v5.arc.codes/blob/master/src/shared/en/aws/quickstart-what-next.md
- v5 https://github.com/architect/v5.arc.codes/blob/master/src/shared/en/aws/quickstart-arc-project-layout.md
- v5 https://github.com/architect/v5.arc.codes/blob/master/src/shared/en/aws/quickstart-install.md

**Comment by brianleroux** [comment]
should note the repo is now here https://github.com/architect/arc.codes.next for dev! we'll move it back here likely when things get stable I assume

**Comment by filmaj** [comment]
So just some thoughts and questions here as I ruminate on the content:

- what is the goal of the document? how does this relate to any existing 'quick start' content (like the 'get started in 30 seconds' content on the home page)? does 'getting started' include deploying to aws or is it just about running locally? aiming for the former means there's a lot we need to flesh out up front (esp. regarding AWS - creds, IAM perms/roles/users/groups)
  - the answer to the above question should help us figure out what secondary / related content to a quick start looks like and how to group the different kinds of content together

some other getting started content to use as a measuring stick:

- https://nextjs.org/learn/basics/getting-started - quite involved; 9 different topics listed under 'basics' (and several others under an 'excel' / more advanced section)
- https://www.gatsbyjs.org/docs/quick-start - very much like the existing arc.codes homepage quickstart. note there's also a more involved tutorial spanning several topics https://www.gatsbyjs.org/tutorial/
- https://serverless.com/framework/docs/getting-started/ not that great, just shows off how to install the tool. there is no tutorial or description of how it works, looks like relies on examples to describe how things work. i would not recommend using this as a template to go on
- https://reactjs.org/docs/getting-started.html#learn-react - i actually really like the react docs as they divide their approach to teaching people how to work with the tool in two ways: learn by doing (via the tutorial) and learn concepts step by step (covering the philosophy / way things work). the way i personally learn is understanding the concepts before i start doing anything.
