### ISSUE TITLE
Link to 'how to use multiple AWS accounts' 404s

### ISSUE THREAD

**Issue by filmaj** [architect/arc.codes#273]
**Describe the issue**
https://arc.codes/guides/multiple-aws-accounts is a 404

**Steps to reproduce**
1. Go to https://arc.codes/reference/arc/aws
2. Click on 'Multiple AWS Accounts'
3. Womp womp

**Comment by brianleroux** [comment]
removed link from `master`… this content moved to `main` … new site coming soon!
