### ISSUE TITLE
Document new @streams format of defining streams

### ISSUE THREAD

**Issue by filmaj** [architect/arc.codes#285]
**Is your feature request related to a problem? Please describe.**
Would be nice to document the new `@streams` pragma, describing the options for custom filepaths for those of us who must toil in transpilationlandia would be nice 😄 

**Describe the solution you'd like**
Probably a new reference section for `@streams`, as well as linking / updating the streams section of the `@tables` docs appropriately, particularly noting that `stream true` is probably going away / deprecated?

**Additional context or notes**
https://github.com/architect/inventory/blob/71d3885a1f84377fa87d7a825e2840cebf547fcf/test/mock/max/app.arc#L55-L60

**Comment by tbeseda** [comment]
cleaning up a bit. this is now canonically named `@tables-streams` and is documented here https://arc.codes/tables-streams
