### ISSUE TITLE
Add `arc.tables` API interface

### ISSUE THREAD

**Issue by filmaj** [architect/arc.codes#332]
Would be nice to see a full description of the `get`, `put`, `query` interface instead of the current 'this is a facade' blurb at https://arc.codes/docs/en/reference/runtime/node#arc.tables:

> The generated client is facade for AWS.DynamoDB.DocumentClient. The delete and get methods take a single parameter that is passed on to the params.Key attribute in the corresponding DocumentClient method. The put method takes a single parameter that is passed on as the params.Item attribute in the DocumentClient.put method. The query, scan, and update methods simply pass the params argument with the TableName parameter prepopulated. See the official DynamoDB documentation for all available parameters.

**Comment by tbeseda** [comment]
Looks like the docs have improved since this issue was filed. There's method reference and a brief example now https://arc.codes/docs/en/reference/runtime/node.js#arc.tables
Thanks!
