### ISSUE TITLE
Documentation: DNS Guides Links Broken

### ISSUE THREAD

**Issue by rubiconjosh** [architect/arc.codes#386]
**Describe the issue**
Specific DNS Guides links in documentation do not work

**Steps to reproduce**
1. Go to: https://arc.codes/docs/en/guides/domains/overview
2. Click on: Any link under DNS Guides
3. See error that says: `NOENT: no such file or directory, open '/var/task/node_modules/@architect/views/docs/en/guides/domains/route53.md'`

**Expected behavior**
Documents located at docs/en/guides/domains/registrars/ should be displayed

**Additional context**
PR incoming

**Comment by macdonst** [comment]
@rubiconjosh thanks for the bug report and PR. We've deployed the fix to the docs site.
