### ISSUE TITLE
Docs don't agree on default node runtime

### ISSUE THREAD

**Issue by macdonst** [architect/arc.codes#399]
In different places on the site we state that nodejs12.x and nodejs14.x is the default runtime for lamdas.

We should do a pass on the docs to make sure they are all up to date and in agreement with each other.

```
[1]: https://arc.codes/docs/en/reference/config.arc/runtime
[2]: https://arc.codes/docs/en/reference/app.arc/aws
```

**Comment by tbeseda** [comment]
And in select places where we mention Node14 it might be worth noting that ES modules, even with `"type": "module"`, are not supported by AWS Lambdas

**Comment by tbeseda** [comment]
Is this one fixed @macdonst ?

**Comment by macdonst** [comment]
@tbeseda yes, it is fixed. Still trying to get a handle on when we close issues:

1. When the code lands in main?
2. When the code is deployed to arc.codes?
