### ISSUE TITLE
Chore: Bump font size down one notch

### ISSUE THREAD

**Issue by macdonst** [architect/arc.codes#407]
The default font size is 18px and we should investigate the readability if we drop it down to 16px.

**Comment by tbeseda** [comment]
think we could make this part of the discussion here? https://github.com/architect/arc.codes/issues/406

**Comment by macdonst** [comment]
I broke this one out specifically since it is a 1 character change and quick scan of about 5 other tech docs site they too seem to use 16px as the base font size. Now that it's been drawn to my attention I can't unsee it.

We can probably make this change now and let folks comment on it in #406.
