### ISSUE TITLE
Awesome macros^H^H^H^H^H^H plugins page

### ISSUE THREAD

**Issue by brianleroux** [architect/arc.codes#432]
possibly content for the site redesign idk but I do know that we should collect these somehow. here's some I've written

- https://github.com/brianleroux/arc-example-macro-sam-policies
- https://github.com/brianleroux/arc-example-cors-macro
- https://github.com/brianleroux/arc-macro-src-folder
- https://github.com/brianleroux/arc-example-macro

**Comment by tbeseda** [comment]
We have moved to plugins with Arc 10 and have examples in both the docs and at https://github.com/architect/plugins
