### ISSUE TITLE
arc.codes app seems slow

### ISSUE THREAD

**Issue by tbeseda** [architect/arc.codes#438]
It _feels_ like the responses are taking longer.
Others have reported multi-second response times -- not good for something that's 100% static.
We should attempt to reproduce locally and attempt some profiling.

**Comment by tbeseda** [comment]
Vastly improved after ditching Shiki.

**Comment by macdonst** [comment]
It's improved for sure but we may want to take another pass on this next week.

**Comment by tbeseda** [comment]
Maybe we come up with a good target render time for the heaviest page (Node.js runtime helper doc?) and open another issue to see how close we can get.

**Comment by macdonst** [comment]
I think the big thing is to look into cold starts especially when you go to https://arc.codes as you can get back to back cold starts as it redirects to another lambda.
