### ISSUE TITLE
config.arc: opt out of shared/views hydration

### ISSUE THREAD

**Issue by tbeseda** [architect/arc.codes#476]
```
// src/http/get-catchall/config.arc
@arc
shared false
views false
```

this opts get /* out of all shared code

> there's also arc env false which disables all userland env vars
> in case you need to super lock down a function

-- @ryanblock via [Arc Discord server](https://discord.gg/y5A2eTsCRX)

**Comment by ryanblock** [comment]
+`env false` to opt out of userland env vars!
