### ISSUE TITLE
clarifications around `npx env` guide

### ISSUE THREAD

**Issue by filmaj** [architect/arc.codes#50]
I have a couple questions regarding `npx env`, and I'm hoping clarifying that in this issue could be a basis for a pull request expanding on the guide. Also feel free to add any ideas that were had around the env guide (there's a mention of the env guide in #41) in here.

My questions:

1. There's mention of 'current working directory' with respect to the `.arc-env` file. I'm probably confused, but there's only one such file per project, right? Not per directory?
2. How do the pragmas in the env file work? The guide mentions `@staging` and `@testing` as different envs. How do those map to typical arc environments? Staging to staging and testing to... also staging? Or does testing = local?

Some ideas around tweaks to the guide:

1. I'd move the section about the arc-env file up higher in the guide. This way references to the file earlier in the doc are, hopefully, clearer.
2. The gif/video at the bottom of the guide lists out an `@production` pragma, which was useful to see. The guide should list that out, too 😄 
3. Re: question 2 above, if testing == local, I would suggest we use consistent terminology. The different environment labels used in `npx env` should also match the same labels in e.g. the `.arc` file `@static` pragmas, or the same labels/env vars used for local testing - in particular, the testing and local labels should be made consistent.

Let me know y'all's thoughts! I am happy to put together a PR that captures the gist of the conversation in here once we settle/agree on some tweaks.

**Comment by filmaj** [comment]
Answering my own questions after playing around some more:

1. one arc-env per project
2. yes testing == local

**Comment by brianleroux** [comment]
> I'd move the section about the arc-env file up higher in the guide. This way references to the file earlier in the doc are, hopefully, clearer.
### 👍 

> The gif/video at the bottom of the guide lists out an @production pragma, which was useful to see. The guide should list that out, too 😄
### 👍 

> Re: question 2 above, if testing == local, I would suggest we use consistent terminology. The different environment labels used in npx env should also match the same labels in e.g. the .arc file @static pragmas, or the same labels/env vars used for local testing - in particular, the testing and local labels should be made consistent.

**Comment by filmaj** [comment]
> Not sure I follow / can you elaborate more?

So the arc-env file will put env vars you want to activate only in the local testing scenario under the `@testing` pragma. But we use the term "local" elsewhere in the project, i.e. the `ARC_LOCAL` env var. We have a "working locally" guide on the site, the static guide says "It's good to work on our local machines, deploy to a staging environment, and promote to production with total confidence that the system is only improving". The env cmd reference confusingly (to me) also says the following about the arc-env file:

> Lists env vars for testing or staging for local dev

I just find the terminology confusing, esp. that last one.

In the end, I work in and deploy to three environments: production, staging, and "local" (via sandbox). Those exact terms are also used in the static guide when describing this delivery flow of local->staging->prod. But the env cmd pragmas throw in `@testing` as a, I think, replacement for "local".

My suggestion is to also change this. Instead of using the term `@testing` for the arc-env file, the env command, and the `npx env` guide, use the term "local".

**Comment by filmaj** [comment]
My thinking behind using 'local' instead of 'testing': I have worked at different companies where they don't call their staging environment 'staging', they call it 'testing'. So I think it's reasonable to assume that referring to a 'testing environment' may be confused with a staging environment, whereas referring to a 'local environment' is, I think, less ambiguous.

fuck man words are hard

**Comment by brianleroux** [comment]
I've seen these things called many things too~! 

For our purposes just expanding on Node best practice of `NODE_ENV` equaling one of `testing`, `staging`, `production` where any of them *could* run locally. (So you maybe have the repl open but its pointing at the production db. or you are previewing the work in sandbox but the data is from staging…etc)

That said, I do get A LOT of folks requesting arbitrary stages. I feel this invites issues w configuration drift. So I think its cool for us to define this and be explicit about the three stages.

**Comment by filmaj** [comment]
oh i had no idea about the node convention

well that throws this for a loop.

i am no longer as convinced of the suggestion to rename testing->local

ill put together a PR for the other changes you thumbs-up'ed, tho

**Comment by brianleroux** [comment]
Yar, for the purposes of posterity and docs I'll elaborate here. `NODE_ENV` a loose convention popularized by legacy Node server apps. For Architect I've striven to make a consistent thing you can depend on. 

There's two facets at play here: authortime and runtime. `NODE_ENV` is for runtime.

You *know* at runtime `process.env.NODE_ENV` will be one of `testing`, `staging` and `production` which keeps it all very easy to reason about while allowing us broad flexibility for introspection/tasks during those different runtime states. Usually logging but the use cases are legion. Not much different than a framework level feature flag really. But the bonus is many Node modules out there in the ecosystem utilize `NODE_ENV` too.

Authortime (or `local` or `development`) is a thing but its meta to dev and sometimes as a dev you need to dig into the various runtime stages (eg we need to read the logs from `production` lambdas or we need to repl into `staging` database tables, etc). Conflating runtime from authortime gets leaky and creates crevices for infrastructure drifts to occur.

We've seen many other verification runtime stages like `qa` and `handoff` and all kinds of ideas out there. Architect strives to be minimalist in implementation and the minimal acceptable hard limit to me is `testing`, `staging` and `production`.

**Comment by filmaj** [comment]
oh man there's also docs under architect/docs for this that describes stuff in a bit more detail, but lots of overlap. lots of overlap between the command help/usage docs in the architect repo, and the arc.codes "workflows" guides.

hmm... I will have a think on how to organize this a bit better..

**Comment by filmaj** [comment]
OK, I've taken a look at all the commands, their help docs in architect, and the guides for the commands on arc.codes.

My thinking:

- keep the CLI help docs (i.e. `npx help env`) focused on purpose, usage and "critical" info around usage (exceptions, that kind of thing). So, all CLI help docs should include high-level description of command _intention_ , example usage (many commands have this, some don't, that's ok we'll get to it) and a full description of all flags for each command. In essence, the CLI help docs are a reference guide and describes the API surface for each command completely.
- have the workflow guides on arc.codes, on the other hand, be more of a 'tutorial' for each command. They can be more verbose and written from a more personal angle. The ascii screencasts you have now fit excellently into this. We can also describe _how_ things work in a bit more detail in the workflow guides (i.e. `npx env`'s `.arc-env` file). Each of these guides should also link to the architect CLI docs for the relevant command, perhaps at the end of the guide, something like "Command Reference: please see the CLI docs _here_ for full usage details" or some such.

So for a concrete example, for `npx env`, its CLI docs should include:

- a complete description of the API:
    - how to add/remove env vars as well as the three env pragmas (testing, staging, production))
    - example usage
- a link to the guide on arc.codes

... whereas the `npx env` guide on arc.codes should include:

- the screencast
- how the `.arc-env` file works
- a link to the doc in the architect repo

WDYT?

**Comment by brianleroux** [comment]
wip but you can preview here https://xm2tr54sk9.execute-api.us-east-1.amazonaws.com/production/

going to start a fresh issue for new docs site
