### ISSUE TITLE
better docs for importance / significance of @app name

### ISSUE THREAD

**Issue by brianleroux** [architect/arc.codes#520]
Got the feedback that changing `@app` name creating a new app was surprising! This is legit, app name is used to derive the CloudFormation stack name which is not mutable. The stack is a unique identifier in the AWS account so a new name is a new app as far as AWS is concerned.

**Comment by tbeseda** [comment]
The existing doc for `@app` is pretty sparse, so this could definitely be an added note there https://arc.codes/app

Where else would an explanation fit? maybe [Deployment](https://arc.codes/docs/en/guides/developer-experience/deployment) ?
