### ISSUE TITLE
[ docs ] Node 18 & @aws-adk v3

### ISSUE THREAD

**Issue by netaisllc** [architect/arc.codes#642]
**Describe the issue**
The docs page  (https://arc.codes/docs/en/get-started/detailed-aws-setup#aws-sdk) says:

```
Lambda Node.js runtimes up to nodejs16.x include AWS SDK v2 (aws-sdk).

As of nodejs18.x, Lambda not includes AWS SDK v3 (@aws-sdk/*).
```

Am I reading the above correctly?  

[This AWS post](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda) seems to state that v3 _is_ supported.

> With this release, Lambda has upgraded the version of the AWS SDK for JavaScript included with the runtime from v2 to v3.

And the `arc.tables` code certainly seems aware of SDK V3.

Being super clear on this topic would be very, very helpful.

**Comment by ryanblock** [comment]
That appears to be a typo. The latest versions of Architect and its helper libs have full support for Lambda running Node.js 18 with AWS SDK v3.
