### ISSUE TITLE
Sandbox: watch and re-copy when src/shared files change

### ISSUE THREAD

**Issue by mikemaccana** [architect/arc.codes#67]
What do y'all think?

 - Use one of those OS-agnostic watcher thingies.
 - Trigger the copy on anything under src/shared - new stuff will get used on next run of each lambda  
 - Have a threshold/delay so it doesn't go nuts during frequent saving

**Comment by brianleroux** [comment]
this is the new behavior in https://github.com/architect/sandbox/blob/master/changelog.md 🎊
