### ISSUE TITLE
GraphQL Guide

### ISSUE THREAD

**Issue by cmbirk** [architect/arc.codes#75]
I'm opening this issue in reference to #41 

I'm just finding out about Architect, but it looks incredible! I'm raising my hand to dive in and learn how to implement GraphQL with it and document it. I wanted to reach out here first and ensure it's possible / practical with the framework. Is that the case? Thanks!

**Comment by kristoferjoseph** [comment]
We've been discussing a GraphQL demo and would appreciate your help.

**Comment by brianleroux** [comment]
hey @cmbirk ! this might help https://gist.github.com/aphex/b66b1cc52f93ae922b55f901ffc1c50f 

I haven't done it myself but I know a few ppl have and would love the help document!

**Comment by cmbirk** [comment]
Perfect!  I'll go ahead and claim this issue. Will get something up / running / documented as soon as I can. Thanks!

**Comment by brianleroux** [comment]
fyi we have an example here https://github.com/begin-examples/node-graphql-api ❤️

**Comment by sergelg90** [comment]
Hey folks! Just discovered Architect and I'm really looking forward to what I can build with it.

On a side note, @brianleroux, this repo doesn't seem to exist anymore (HTTP 404). 

> fyi we have an example here https://github.com/begin-examples/node-graphql-api

Or maybe it's not public?

**Comment by ryanblock** [comment]
Nice! That repo was renamed to: https://github.com/begin-examples/node-apollo (sorry it didn't forward!)
