### ISSUE TITLE
Issues with Persist Data tutorial

### ISSUE THREAD

**Issue by pcaisse** [architect/arc.codes#83]
I uncovered a number of issues when going through the [Persist Data](https://arc.codes/guides/data) tutorial:

* Layout path is referenced incorrectly (`layout = require('@architect/shared/layout')` vs within `views` dir)
* Missing source code for `make-note.js` (this file is required but is not mentioned)
* Static files in `public/` are not mentioned in tutorial (there is no `@static` in the `.arc` file), but are needed for images and styles
* Email placeholder in text input initially shows up as `undefined` (just needs an `|| ''`)
* No mention of installing `bcrypt` in tutorial (needs to be installed for each lambda that uses it)
* `bcrypt` also requires its non-JS dependencies to be compiled separately (ended up using the `bcryptjs` which is the JS-only equivalent to avoid this step)
* Logo's path needs to be `let logo = arc.http.helpers.static('/images/logo.svg')` (path was missing leading slash)

**Comment by brianleroux** [comment]
thx for this!

**Comment by brianleroux** [comment]
appears most of these are now resolved but lmk if we're missing anything
