### ISSUE TITLE
Getting started should favour local instead of AWS

### ISSUE THREAD

**Issue by jonathanstiansen** [architect/arc.codes#92]
Some things to add:

The `prerequisites` page talking about setting up AWS creds is before a `try us out` page, should probably be reversed. It's going to help adoption if we walk through local setup  instead of setting up IAM creds before you can write code. Many people will likely stop there.

[Installation page](https://arc.codes/quickstart/install) should also have `npx create local` to enable people to create local resources without having creds. See https://github.com/arc-repos/architect/issues/339.

Thanks guys!

**Comment by brianleroux** [comment]
this is the default in architect 6.x! its early and the docs are wip but you can preview them here https://xm2tr54sk9.execute-api.us-east-1.amazonaws.com/production/
